import WorkoutScheduleStore from '../store/WorkoutScheduleStore';
// ...existing code...

function createWorkoutSchedule(options) {
    // ...existing code...
    const selectedCategories = WorkoutScheduleStore.getSelectedWorkoutCategories();
    console.log('Selected categories:', selectedCategories);
    // ...existing code...
}

// ...existing code...

function saveWorkoutSchedule(schedule) {
    // ...existing code...
    WorkoutScheduleStore.saveSelectedWorkoutCategories(schedule.selectedCategories);
    // ...existing code...
}

// ...existing code...
