import { DEFAULT_ENTITY_VERSION } from '../lifecycle';
import type { MissionEntityCollection } from '../types';
import type { OperationStep } from './operationAlpha';

const BASE_TS = '2026-03-07T09:00:00.000Z';

export const operationCharlieStepSequence: OperationStep[] = [
    { id: 'charlie-brief', label: 'Brief: define artifact-chain objective and integrity constraints', routePath: '/mission/brief' },
    { id: 'charlie-triage', label: 'Triage: identify highest-risk artifact dependencies', routePath: '/mission/triage' },
    { id: 'charlie-case', label: 'Case: traverse artifact chain and confirm ordering', routePath: '/mission/case' },
    { id: 'charlie-signal', label: 'Signal: validate dependency breakpoints and branch outcomes', routePath: '/mission/signal' },
    { id: 'charlie-checklist', label: 'Checklist: execute containment tasks in dependency order', routePath: '/mission/checklist' },
    { id: 'charlie-debrief', label: 'Debrief: record artifact-traceability decisions and readiness impact', routePath: '/mission/debrief' },
];

export const operationCharlieCollection: MissionEntityCollection = {
    operations: [
        {
            kind: 'operation',
            id: 'op-operation-charlie',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            codename: 'Operation Charlie',
            objective: 'Resolve artifact dependency conflicts while preserving a complete decision trace from source capture to debrief.',
            status: 'active',
            readinessScore: 84,
            caseIds: ['case-charlie-artifact-chain'],
            signalIds: ['signal-charlie-chain-gap', 'signal-charlie-hash-drift', 'signal-charlie-origin-conflict'],
            checklistIds: ['checklist-operation-charlie-chain'],
            debriefOutcomeId: 'debrief-operation-charlie',
        },
    ],
    cases: [
        {
            kind: 'case',
            id: 'case-charlie-artifact-chain',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            operationId: 'op-operation-charlie',
            title: 'Artifact Chain Integrity',
            summary: 'A dependent evidence chain is fragmented by missing links and conflicting origin metadata.',
            status: 'engaged',
            severity: 'critical',
            leadIds: ['lead-charlie-chain-sequencing', 'lead-charlie-origin-verification'],
            signalIds: ['signal-charlie-chain-gap', 'signal-charlie-hash-drift', 'signal-charlie-origin-conflict'],
            artifactIds: [
                'artifact-charlie-ingress-capture',
                'artifact-charlie-parser-log',
                'artifact-charlie-origin-report',
                'artifact-charlie-escalation-note',
            ],
        },
    ],
    leads: [
        {
            kind: 'lead',
            id: 'lead-charlie-chain-sequencing',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            caseId: 'case-charlie-artifact-chain',
            title: 'Artifact sequencing lead',
            detail: 'Restore artifact ordering by linking ingress capture to parser output before escalation.',
            status: 'qualified',
            confidence: 0.83,
            source: 'system',
        },
        {
            kind: 'lead',
            id: 'lead-charlie-origin-verification',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            caseId: 'case-charlie-artifact-chain',
            title: 'Origin verification lead',
            detail: 'Resolve conflicting origin markers and confirm trusted source before release.',
            status: 'new',
            confidence: 0.7,
            source: 'external',
        },
    ],
    signals: [
        {
            kind: 'signal',
            id: 'signal-charlie-chain-gap',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            operationId: 'op-operation-charlie',
            caseId: 'case-charlie-artifact-chain',
            title: 'Artifact chain gap detected',
            detail: 'Dependency link between parser log and origin report is missing in current sequence.',
            status: 'investigating',
            severity: 'critical',
            source: 'system',
            observedAt: '2026-03-07T09:06:00.000Z',
        },
        {
            kind: 'signal',
            id: 'signal-charlie-hash-drift',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            operationId: 'op-operation-charlie',
            caseId: 'case-charlie-artifact-chain',
            title: 'Hash drift in dependent artifact',
            detail: 'Parser output hash no longer matches ingress-capture lineage expectations.',
            status: 'new',
            severity: 'high',
            source: 'sensor',
            observedAt: '2026-03-07T09:08:00.000Z',
        },
        {
            kind: 'signal',
            id: 'signal-charlie-origin-conflict',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            operationId: 'op-operation-charlie',
            caseId: 'case-charlie-artifact-chain',
            title: 'Conflicting artifact origin markers',
            detail: 'Origin report references two possible source systems, requiring validation before dissemination.',
            status: 'acknowledged',
            severity: 'high',
            source: 'intel',
            observedAt: '2026-03-07T09:10:00.000Z',
        },
    ],
    artifacts: [
        {
            kind: 'artifact',
            id: 'artifact-charlie-ingress-capture',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            caseId: 'case-charlie-artifact-chain',
            title: 'Ingress capture segment',
            description: 'Initial capture that anchors the artifact dependency chain.',
            artifactType: 'capture',
            source: 'edge-sensor-04',
            hash: 'sha256:charlie001capture',
            collectedAt: '2026-03-07T09:03:00.000Z',
        },
        {
            kind: 'artifact',
            id: 'artifact-charlie-parser-log',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            caseId: 'case-charlie-artifact-chain',
            title: 'Parser transformation log',
            description: 'Transformation log that should link directly to ingress capture hash lineage.',
            artifactType: 'log',
            source: 'analysis-pipeline',
            hash: 'sha256:charlie002parser',
            collectedAt: '2026-03-07T09:05:00.000Z',
        },
        {
            kind: 'artifact',
            id: 'artifact-charlie-origin-report',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            caseId: 'case-charlie-artifact-chain',
            title: 'Origin attribution report',
            description: 'Attribution report dependent on parser lineage and source-system integrity.',
            artifactType: 'report',
            source: 'intel-desk',
            hash: 'sha256:charlie003origin',
            collectedAt: '2026-03-07T09:09:00.000Z',
        },
        {
            kind: 'artifact',
            id: 'artifact-charlie-escalation-note',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            caseId: 'case-charlie-artifact-chain',
            title: 'Escalation dependency note',
            description: 'Operator note documenting accepted chain state before escalation release.',
            artifactType: 'note',
            source: 'ops-desk',
            collectedAt: '2026-03-07T09:12:00.000Z',
        },
    ],
    intelPackets: [
        {
            kind: 'intel_packet',
            id: 'intel-operation-charlie-chain',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            operationId: 'op-operation-charlie',
            title: 'Operation Charlie dependency packet',
            summary: 'Dependency-ordered artifact packet used to verify traceability before mission escalation.',
            status: 'validated',
            artifactIds: [
                'artifact-charlie-ingress-capture',
                'artifact-charlie-parser-log',
                'artifact-charlie-origin-report',
                'artifact-charlie-escalation-note',
            ],
            classification: 'confidential',
        },
    ],
    debriefOutcomes: [
        {
            kind: 'debrief_outcome',
            id: 'debrief-operation-charlie',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: '2026-03-07T10:00:00.000Z',
            operationId: 'op-operation-charlie',
            summary: 'Artifact-chain dependencies were restored and decision traceability was preserved through debrief.',
            lessonsLearned: [
                'Treat missing dependency links as critical before final escalation.',
                'Verify origin metadata consistency before publishing attribution reports.',
            ],
            followUpActions: [
                'Add automatic dependency-chain validation checks during case review.',
                'Integrate dependency confidence scores into progression modeling.',
            ],
            rating: 'strong',
            readinessDelta: 8,
        },
    ],
};
