import { DEFAULT_ENTITY_VERSION } from '../lifecycle';
import type { MissionEntityCollection } from '../types';

const BASE_TS = '2026-03-05T08:00:00.000Z';

export type OperationStep = {
    id: string;
    label: string;
    routePath: '/mission/brief' | '/mission/triage' | '/mission/case' | '/mission/signal' | '/mission/checklist' | '/mission/debrief';
};

export const operationAlphaStepSequence: OperationStep[] = [
    { id: 'alpha-brief', label: 'Brief: confirm relay outage constraints and objective', routePath: '/mission/brief' },
    { id: 'alpha-triage', label: 'Triage: prioritize beacon and gateway alerts', routePath: '/mission/triage' },
    { id: 'alpha-case', label: 'Case: validate evidence chain and escalation threshold', routePath: '/mission/case' },
    { id: 'alpha-signal', label: 'Signal: acknowledge hostile burst and assign owner', routePath: '/mission/signal' },
    { id: 'alpha-checklist', label: 'Checklist: run containment and comms confirmation', routePath: '/mission/checklist' },
    { id: 'alpha-debrief', label: 'Debrief: record decision quality and readiness delta', routePath: '/mission/debrief' },
];

export const operationAlphaCollection: MissionEntityCollection = {
    operations: [
        {
            kind: 'operation',
            id: 'op-operation-alpha',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            codename: 'Operation Alpha',
            objective: 'Contain relay corridor compromise while preserving attribution evidence for debrief.',
            status: 'briefing',
            readinessScore: 78,
            caseIds: ['case-alpha-relay-corridor'],
            signalIds: ['signal-alpha-beacon-surge', 'signal-alpha-gateway-drift'],
            checklistIds: ['checklist-operation-alpha-core'],
            debriefOutcomeId: 'debrief-operation-alpha',
        },
    ],
    cases: [
        {
            kind: 'case',
            id: 'case-alpha-relay-corridor',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            operationId: 'op-operation-alpha',
            title: 'Relay Corridor Intercept',
            summary: 'An adversary replayed stale gateway certificates to mask command relays near sector ingress.',
            status: 'assessing',
            severity: 'high',
            leadIds: ['lead-alpha-gateway-cert', 'lead-alpha-operator-window'],
            signalIds: ['signal-alpha-beacon-surge', 'signal-alpha-gateway-drift'],
            artifactIds: ['artifact-alpha-pcap', 'artifact-alpha-auth-report', 'artifact-alpha-comms-note'],
        },
    ],
    leads: [
        {
            kind: 'lead',
            id: 'lead-alpha-gateway-cert',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            caseId: 'case-alpha-relay-corridor',
            title: 'Gateway certificate replay path',
            detail: 'Compare certificate chain rollover against relay beacon timestamps for adversary foothold windows.',
            status: 'qualified',
            confidence: 0.82,
            source: 'system',
        },
        {
            kind: 'lead',
            id: 'lead-alpha-operator-window',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            caseId: 'case-alpha-relay-corridor',
            title: 'Operator handoff timing',
            detail: 'Validate whether relay handoff occurred during reduced staffing and delayed acknowledgements.',
            status: 'new',
            confidence: 0.67,
            source: 'human',
        },
    ],
    signals: [
        {
            kind: 'signal',
            id: 'signal-alpha-beacon-surge',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            operationId: 'op-operation-alpha',
            caseId: 'case-alpha-relay-corridor',
            title: 'Beacon surge on relay ingress',
            detail: 'Ingress beacon volume exceeded baseline by 280% after stale token replay.',
            status: 'acknowledged',
            severity: 'critical',
            source: 'sensor',
            observedAt: '2026-03-05T08:11:00.000Z',
        },
        {
            kind: 'signal',
            id: 'signal-alpha-gateway-drift',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            operationId: 'op-operation-alpha',
            caseId: 'case-alpha-relay-corridor',
            title: 'Gateway trust drift',
            detail: 'Trust anchor drift observed across two edge gateways after emergency failover.',
            status: 'investigating',
            severity: 'high',
            source: 'intel',
            observedAt: '2026-03-05T08:18:00.000Z',
        },
    ],
    artifacts: [
        {
            kind: 'artifact',
            id: 'artifact-alpha-pcap',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            caseId: 'case-alpha-relay-corridor',
            title: 'Relay ingress packet capture',
            description: 'Packet capture of replay window containing duplicated certificate negotiation frames.',
            artifactType: 'capture',
            source: 'sensor-hub-12',
            hash: 'sha256:alpha001pcap',
            collectedAt: '2026-03-05T08:14:00.000Z',
        },
        {
            kind: 'artifact',
            id: 'artifact-alpha-auth-report',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            caseId: 'case-alpha-relay-corridor',
            title: 'Gateway auth drift report',
            description: 'Automated report of trust-anchor mismatches across failover nodes.',
            artifactType: 'report',
            source: 'gateway-audit',
            hash: 'sha256:alpha002report',
            collectedAt: '2026-03-05T08:19:00.000Z',
        },
        {
            kind: 'artifact',
            id: 'artifact-alpha-comms-note',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            caseId: 'case-alpha-relay-corridor',
            title: 'Ops handoff comms note',
            description: 'Shift handoff note confirming delayed acknowledgement during window of compromise.',
            artifactType: 'note',
            source: 'ops-desk',
            collectedAt: '2026-03-05T08:22:00.000Z',
        },
    ],
    intelPackets: [
        {
            kind: 'intel_packet',
            id: 'intel-operation-alpha-brief',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            operationId: 'op-operation-alpha',
            title: 'Operation Alpha triage packet',
            summary: 'Introductory triage packet outlining signal priority, artifact chain, and escalation boundaries.',
            status: 'validated',
            artifactIds: ['artifact-alpha-pcap', 'artifact-alpha-auth-report'],
            classification: 'restricted',
        },
    ],
    debriefOutcomes: [
        {
            kind: 'debrief_outcome',
            id: 'debrief-operation-alpha',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: '2026-03-05T09:00:00.000Z',
            operationId: 'op-operation-alpha',
            summary: 'Relay corridor stabilized, evidence retained, and escalation timing improved after signal acknowledgement.',
            lessonsLearned: [
                'Acknowledge high-severity ingress surges before trust-anchor analysis begins.',
                'Use single-owner signal assignment to reduce duplicate containment actions.',
            ],
            followUpActions: [
                'Add relay certificate replay alert to baseline watchlist.',
                'Run Operation Bravo for deeper signal branch analysis.',
            ],
            rating: 'strong',
            readinessDelta: 7,
        },
    ],
};
