import { DEFAULT_ENTITY_VERSION } from '../lifecycle';
import type { MissionEntityCollection } from '../types';
import type { OperationStep } from './operationAlpha';

const BASE_TS = '2026-03-06T10:00:00.000Z';

export const operationBravoStepSequence: OperationStep[] = [
    { id: 'bravo-brief', label: 'Brief: establish signal-analysis objective and branch criteria', routePath: '/mission/brief' },
    { id: 'bravo-triage', label: 'Triage: rank multi-source alerts by severity and confidence', routePath: '/mission/triage' },
    { id: 'bravo-case', label: 'Case: map branch hypotheses to supporting artifacts', routePath: '/mission/case' },
    { id: 'bravo-signal', label: 'Signal: execute branch decisions (escalate, monitor, dismiss)', routePath: '/mission/signal' },
    { id: 'bravo-checklist', label: 'Checklist: confirm branch action ownership and timing', routePath: '/mission/checklist' },
    { id: 'bravo-debrief', label: 'Debrief: assess branch quality and readiness impact', routePath: '/mission/debrief' },
];

export const operationBravoCollection: MissionEntityCollection = {
    operations: [
        {
            kind: 'operation',
            id: 'op-operation-bravo',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            codename: 'Operation Bravo',
            objective: 'Resolve a high-volume signal cascade by selecting and validating analysis branches under time pressure.',
            status: 'triage',
            readinessScore: 81,
            caseIds: ['case-bravo-signal-cascade'],
            signalIds: [
                'signal-bravo-gateway-flood',
                'signal-bravo-auth-anomaly',
                'signal-bravo-route-hijack',
                'signal-bravo-recovery-false-positive',
            ],
            checklistIds: ['checklist-operation-bravo-branches'],
            debriefOutcomeId: 'debrief-operation-bravo',
        },
    ],
    cases: [
        {
            kind: 'case',
            id: 'case-bravo-signal-cascade',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            operationId: 'op-operation-bravo',
            title: 'Signal Cascade Validation',
            summary: 'Correlated alerts indicate a potential route hijack mixed with noisy recovery chatter.',
            status: 'engaged',
            severity: 'critical',
            leadIds: ['lead-bravo-auth-chain', 'lead-bravo-route-integrity', 'lead-bravo-recovery-noise'],
            signalIds: [
                'signal-bravo-gateway-flood',
                'signal-bravo-auth-anomaly',
                'signal-bravo-route-hijack',
                'signal-bravo-recovery-false-positive',
            ],
            artifactIds: ['artifact-bravo-correlation-report', 'artifact-bravo-route-diff', 'artifact-bravo-ops-log'],
        },
    ],
    leads: [
        {
            kind: 'lead',
            id: 'lead-bravo-auth-chain',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            caseId: 'case-bravo-signal-cascade',
            title: 'Auth-chain divergence branch',
            detail: 'Branch A: validate auth drift against known maintenance windows before escalation.',
            status: 'qualified',
            confidence: 0.79,
            source: 'external',
        },
        {
            kind: 'lead',
            id: 'lead-bravo-route-integrity',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            caseId: 'case-bravo-signal-cascade',
            title: 'Route-integrity compromise branch',
            detail: 'Branch B: confirm route advertisement tampering and trigger immediate containment if confirmed.',
            status: 'new',
            confidence: 0.72,
            source: 'sensor',
        },
        {
            kind: 'lead',
            id: 'lead-bravo-recovery-noise',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            caseId: 'case-bravo-signal-cascade',
            title: 'Recovery false-positive branch',
            detail: 'Branch C: detect rollback artifacts that mimic compromise and should be monitored, not escalated.',
            status: 'new',
            confidence: 0.61,
            source: 'system',
        },
    ],
    signals: [
        {
            kind: 'signal',
            id: 'signal-bravo-gateway-flood',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            operationId: 'op-operation-bravo',
            caseId: 'case-bravo-signal-cascade',
            title: 'Gateway flood burst',
            detail: 'Ingress gateways report synchronized flood behavior across four sectors.',
            status: 'acknowledged',
            severity: 'critical',
            source: 'sensor',
            observedAt: '2026-03-06T10:05:00.000Z',
        },
        {
            kind: 'signal',
            id: 'signal-bravo-auth-anomaly',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            operationId: 'op-operation-bravo',
            caseId: 'case-bravo-signal-cascade',
            title: 'Auth-token anomaly cluster',
            detail: 'Token replay signatures appear in staggered waves from two external peers.',
            status: 'investigating',
            severity: 'high',
            source: 'intel',
            observedAt: '2026-03-06T10:07:00.000Z',
        },
        {
            kind: 'signal',
            id: 'signal-bravo-route-hijack',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            operationId: 'op-operation-bravo',
            caseId: 'case-bravo-signal-cascade',
            title: 'Route advertisement hijack',
            detail: 'Upstream route advertisements diverge from baseline and reroute sensitive egress traffic.',
            status: 'new',
            severity: 'critical',
            source: 'system',
            observedAt: '2026-03-06T10:09:00.000Z',
        },
        {
            kind: 'signal',
            id: 'signal-bravo-recovery-false-positive',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            operationId: 'op-operation-bravo',
            caseId: 'case-bravo-signal-cascade',
            title: 'Recovery replay false positive',
            detail: 'Rollback script replay produced benign alerts overlapping with adversary indicators.',
            status: 'new',
            severity: 'medium',
            source: 'operator',
            observedAt: '2026-03-06T10:12:00.000Z',
        },
    ],
    artifacts: [
        {
            kind: 'artifact',
            id: 'artifact-bravo-correlation-report',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            caseId: 'case-bravo-signal-cascade',
            title: 'Signal correlation report',
            description: 'Correlates flood, auth, and route events into candidate branch outcomes.',
            artifactType: 'report',
            source: 'analysis-core',
            hash: 'sha256:bravo001corr',
            collectedAt: '2026-03-06T10:15:00.000Z',
        },
        {
            kind: 'artifact',
            id: 'artifact-bravo-route-diff',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            caseId: 'case-bravo-signal-cascade',
            title: 'Route diff snapshot',
            description: 'Snapshot diff of affected route advertisements during suspected hijack window.',
            artifactType: 'indicator',
            source: 'route-monitor',
            hash: 'sha256:bravo002route',
            collectedAt: '2026-03-06T10:16:00.000Z',
        },
        {
            kind: 'artifact',
            id: 'artifact-bravo-ops-log',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            caseId: 'case-bravo-signal-cascade',
            title: 'Ops branch decision log',
            description: 'Timestamped branch decisions with assigned owners and escalation results.',
            artifactType: 'log',
            source: 'ops-desk',
            collectedAt: '2026-03-06T10:18:00.000Z',
        },
    ],
    intelPackets: [
        {
            kind: 'intel_packet',
            id: 'intel-operation-bravo-branches',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: BASE_TS,
            operationId: 'op-operation-bravo',
            title: 'Operation Bravo branch matrix',
            summary: 'Branch matrix mapping each signal to escalate, monitor, or dismiss outcomes.',
            status: 'validated',
            artifactIds: ['artifact-bravo-correlation-report', 'artifact-bravo-route-diff', 'artifact-bravo-ops-log'],
            classification: 'restricted',
        },
    ],
    debriefOutcomes: [
        {
            kind: 'debrief_outcome',
            id: 'debrief-operation-bravo',
            version: DEFAULT_ENTITY_VERSION,
            createdAt: BASE_TS,
            updatedAt: '2026-03-06T11:00:00.000Z',
            operationId: 'op-operation-bravo',
            summary: 'Signal-heavy branch analysis reduced false escalations while preserving critical containment speed.',
            lessonsLearned: [
                'Use branch criteria before actioning medium-confidence alerts.',
                'Pair route-diff evidence with auth anomalies before declaring compromise.',
            ],
            followUpActions: [
                'Automate branch assignment hints in signal queue.',
                'Run Operation Charlie to validate artifact-chain decisions.',
            ],
            rating: 'strong',
            readinessDelta: 6,
        },
    ],
};
