import type { TrainingSubModuleFile, TrainingModuleFile, CardDeckFile } from "../types/TrainingDataFiles";

const manifestUrl = "/training_modules_manifest.json";

type ManifestEntry = { id: string; shard: string; hash?: string; size?: number; version?: string };
type Manifest = { generatedAt?: string; version?: string; modules: ManifestEntry[] };
type Shard = { module: TrainingModuleFile; subModules: Record<string, TrainingSubModuleFile>; cardDecks: Record<string, CardDeckFile> };

let manifestPromise: Promise<Manifest> | null = null;
const loadManifest = async (): Promise<Manifest> => {
    if (!manifestPromise) {
        manifestPromise = fetch(manifestUrl).then(async (res) => {
            if (!res.ok) throw new Error(`Failed to load manifest: ${res.status}`);
            return res.json();
        });
    }
    return manifestPromise;
};

const versionedCacheKey = (entry: ManifestEntry) => `${entry.id}@${entry.hash ?? entry.version ?? entry.size ?? "v0"}`;
const shardCache = new Map<string, Promise<Shard>>();
const loadShard = async (id: string): Promise<Shard> => {
    const manifest = await loadManifest();
    const entry = manifest.modules.find((m) => m.id === id);
    if (!entry) throw new Error('Shard not found for module ' + id);
    const cacheKey = versionedCacheKey(entry);
    if (!shardCache.has(cacheKey)) {
        shardCache.set(cacheKey, fetch(entry.shard).then(async (res) => {
            if (!res.ok) throw new Error('Failed to load shard ' + id + ': ' + res.status);
            return res.json();
        }));
    }
    return shardCache.get(cacheKey)!;
};

export const subModulePaths = {
    agencies_cia_training: async () => (await loadShard("agencies")).subModules["agencies_cia_training"],
    agencies_fbi_training: async () => (await loadShard("agencies")).subModules["agencies_fbi_training"],
    agencies_homeland_security: async () => (await loadShard("agencies")).subModules["agencies_homeland_security"],
    agencies_interpol_training: async () => (await loadShard("agencies")).subModules["agencies_interpol_training"],
    agencies_secret_service: async () => (await loadShard("agencies")).subModules["agencies_secret_service"],
    combat_close_quarters_combat: async () => (await loadShard("combat")).subModules["combat_close_quarters_combat"],
    combat_combat_scenario_simulation: async () => (await loadShard("combat")).subModules["combat_combat_scenario_simulation"],
    combat_firearms_training: async () => (await loadShard("combat")).subModules["combat_firearms_training"],
    combat_melee_weapons_training: async () => (await loadShard("combat")).subModules["combat_melee_weapons_training"],
    combat_stealth_and_escape_tactics: async () => (await loadShard("combat")).subModules["combat_stealth_and_escape_tactics"],
    combat_tactical_movement: async () => (await loadShard("combat")).subModules["combat_tactical_movement"],
    counter_biochem_biochem_defense_protocols: async () => (await loadShard("counter_biochem")).subModules["counter_biochem_biochem_defense_protocols"],
    counter_biochem_biochem_survival_medicine: async () => (await loadShard("counter_biochem")).subModules["counter_biochem_biochem_survival_medicine"],
    counter_biochem_contagion_containment_strategies: async () => (await loadShard("counter_biochem")).subModules["counter_biochem_contagion_containment_strategies"],
    counter_biochem_food_water_supply_protection: async () => (await loadShard("counter_biochem")).subModules["counter_biochem_food_water_supply_protection"],
    counter_biochem_medical_psyops_resistance: async () => (await loadShard("counter_biochem")).subModules["counter_biochem_medical_psyops_resistance"],
    counter_biochem_toxin_neutralization_tactics: async () => (await loadShard("counter_biochem")).subModules["counter_biochem_toxin_neutralization_tactics"],
    counter_psyops_cyber_psyops_digital_warfare_defense: async () => (await loadShard("counter_psyops")).subModules["counter_psyops_cyber_psyops_digital_warfare_defense"],
    counter_psyops_disinformation_analysis: async () => (await loadShard("counter_psyops")).subModules["counter_psyops_disinformation_analysis"],
    counter_psyops_elite_power_structure_analysis: async () => (await loadShard("counter_psyops")).subModules["counter_psyops_elite_power_structure_analysis"],
    counter_psyops_emotional_resilience_training: async () => (await loadShard("counter_psyops")).subModules["counter_psyops_emotional_resilience_training"],
    counter_psyops_manipulation_detection: async () => (await loadShard("counter_psyops")).subModules["counter_psyops_manipulation_detection"],
    counter_psyops_mind_hacking_countermeasures: async () => (await loadShard("counter_psyops")).subModules["counter_psyops_mind_hacking_countermeasures"],
    counter_psyops_narrative_warfare_mass_awakening: async () => (await loadShard("counter_psyops")).subModules["counter_psyops_narrative_warfare_mass_awakening"],
    counter_psyops_propaganda_countermeasures: async () => (await loadShard("counter_psyops")).subModules["counter_psyops_propaganda_countermeasures"],
    counter_psyops_psychological_warfare_defense: async () => (await loadShard("counter_psyops")).subModules["counter_psyops_psychological_warfare_defense"],
    cybersecurity_digital_forensics: async () => (await loadShard("cybersecurity")).subModules["cybersecurity_digital_forensics"],
    cybersecurity_history_of_cybersecurity: async () => (await loadShard("cybersecurity")).subModules["cybersecurity_history_of_cybersecurity"],
    cybersecurity_malware_analysis: async () => (await loadShard("cybersecurity")).subModules["cybersecurity_malware_analysis"],
    cybersecurity_network_security: async () => (await loadShard("cybersecurity")).subModules["cybersecurity_network_security"],
    cybersecurity_penetration_testing: async () => (await loadShard("cybersecurity")).subModules["cybersecurity_penetration_testing"],
    cybersecurity_social_engineering_defense: async () => (await loadShard("cybersecurity")).subModules["cybersecurity_social_engineering_defense"],
    cybersecurity_threat_intelligence: async () => (await loadShard("cybersecurity")).subModules["cybersecurity_threat_intelligence"],
    dance_breakdance: async () => (await loadShard("dance")).subModules["dance_breakdance"],
    dance_contact_staff_flow: async () => (await loadShard("dance")).subModules["dance_contact_staff_flow"],
    dance_cutting_shapes: async () => (await loadShard("dance")).subModules["dance_cutting_shapes"],
    dance_dubstep_glitch: async () => (await loadShard("dance")).subModules["dance_dubstep_glitch"],
    dance_fan_dancing: async () => (await loadShard("dance")).subModules["dance_fan_dancing"],
    dance_freestyle_rave: async () => (await loadShard("dance")).subModules["dance_freestyle_rave"],
    dance_gloving_tutting: async () => (await loadShard("dance")).subModules["dance_gloving_tutting"],
    dance_industrial_dance: async () => (await loadShard("dance")).subModules["dance_industrial_dance"],
    dance_jumpstyle_hardstyle: async () => (await loadShard("dance")).subModules["dance_jumpstyle_hardstyle"],
    dance_liquid_dance: async () => (await loadShard("dance")).subModules["dance_liquid_dance"],
    dance_poi_spinning: async () => (await loadShard("dance")).subModules["dance_poi_spinning"],
    equations_abstract_mathematical_models: async () => (await loadShard("equations")).subModules["equations_abstract_mathematical_models"],
    equations_algebraic_structure_analysis: async () => (await loadShard("equations")).subModules["equations_algebraic_structure_analysis"],
    equations_bioelectric_psionic_tech: async () => (await loadShard("equations")).subModules["equations_bioelectric_psionic_tech"],
    equations_calculus_and_rate_of_change: async () => (await loadShard("equations")).subModules["equations_calculus_and_rate_of_change"],
    equations_electrogravitics_and_field_propulsion: async () => (await loadShard("equations")).subModules["equations_electrogravitics_and_field_propulsion"],
    equations_hyperdimensional_mathematics: async () => (await loadShard("equations")).subModules["equations_hyperdimensional_mathematics"],
    equations_mathematical_notation_fundamentals: async () => (await loadShard("equations")).subModules["equations_mathematical_notation_fundamentals"],
    equations_neural_network_mathematics: async () => (await loadShard("equations")).subModules["equations_neural_network_mathematics"],
    equations_physics_equations_and_applications: async () => (await loadShard("equations")).subModules["equations_physics_equations_and_applications"],
    equations_quantum_psionics: async () => (await loadShard("equations")).subModules["equations_quantum_psionics"],
    equations_symbolic_logic_and_proofs: async () => (await loadShard("equations")).subModules["equations_symbolic_logic_and_proofs"],
    equations_temporal_mechanics: async () => (await loadShard("equations")).subModules["equations_temporal_mechanics"],
    espionage_clandestine_surveillance: async () => (await loadShard("espionage")).subModules["espionage_clandestine_surveillance"],
    espionage_counterintelligence: async () => (await loadShard("espionage")).subModules["espionage_counterintelligence"],
    espionage_covert_operations: async () => (await loadShard("espionage")).subModules["espionage_covert_operations"],
    espionage_disguise_and_identity: async () => (await loadShard("espionage")).subModules["espionage_disguise_and_identity"],
    espionage_psychological_manipulation: async () => (await loadShard("espionage")).subModules["espionage_psychological_manipulation"],
    espionage_tradecraft: async () => (await loadShard("espionage")).subModules["espionage_tradecraft"],
    fitness_athletic_performance: async () => (await loadShard("fitness")).subModules["fitness_athletic_performance"],
    fitness_balance_and_stability: async () => (await loadShard("fitness")).subModules["fitness_balance_and_stability"],
    fitness_calisthenics: async () => (await loadShard("fitness")).subModules["fitness_calisthenics"],
    fitness_cardiovascular_endurance: async () => (await loadShard("fitness")).subModules["fitness_cardiovascular_endurance"],
    fitness_core_strengthening: async () => (await loadShard("fitness")).subModules["fitness_core_strengthening"],
    fitness_flexibility_and_mobility: async () => (await loadShard("fitness")).subModules["fitness_flexibility_and_mobility"],
    fitness_functional_fitness: async () => (await loadShard("fitness")).subModules["fitness_functional_fitness"],
    fitness_high_intensity_interval_training: async () => (await loadShard("fitness")).subModules["fitness_high_intensity_interval_training"],
    fitness_mind_body_fitness: async () => (await loadShard("fitness")).subModules["fitness_mind_body_fitness"],
    fitness_recovery_and_injury_prevention: async () => (await loadShard("fitness")).subModules["fitness_recovery_and_injury_prevention"],
    fitness_speed_and_agility: async () => (await loadShard("fitness")).subModules["fitness_speed_and_agility"],
    fitness_strength_training: async () => (await loadShard("fitness")).subModules["fitness_strength_training"],
    intelligence_behavioral_profiling: async () => (await loadShard("intelligence")).subModules["intelligence_behavioral_profiling"],
    intelligence_cyber_intelligence: async () => (await loadShard("intelligence")).subModules["intelligence_cyber_intelligence"],
    intelligence_intelligence_analysis: async () => (await loadShard("intelligence")).subModules["intelligence_intelligence_analysis"],
    intelligence_linguistic_analysis: async () => (await loadShard("intelligence")).subModules["intelligence_linguistic_analysis"],
    intelligence_open_source_intelligence: async () => (await loadShard("intelligence")).subModules["intelligence_open_source_intelligence"],
    intelligence_strategic_forecasting: async () => (await loadShard("intelligence")).subModules["intelligence_strategic_forecasting"],
    investigation_criminal_profiling: async () => (await loadShard("investigation")).subModules["investigation_criminal_profiling"],
    investigation_cybercrime_analysis: async () => (await loadShard("investigation")).subModules["investigation_cybercrime_analysis"],
    investigation_digital_forensics: async () => (await loadShard("investigation")).subModules["investigation_digital_forensics"],
    investigation_financial_crimes: async () => (await loadShard("investigation")).subModules["investigation_financial_crimes"],
    investigation_forensic_investigation: async () => (await loadShard("investigation")).subModules["investigation_forensic_investigation"],
    investigation_homicide_investigation: async () => (await loadShard("investigation")).subModules["investigation_homicide_investigation"],
    martial_arts_baguazhang: async () => (await loadShard("martial_arts")).subModules["martial_arts_baguazhang"],
    martial_arts_capoeira: async () => (await loadShard("martial_arts")).subModules["martial_arts_capoeira"],
    martial_arts_hapkido: async () => (await loadShard("martial_arts")).subModules["martial_arts_hapkido"],
    martial_arts_jeet_kune_do: async () => (await loadShard("martial_arts")).subModules["martial_arts_jeet_kune_do"],
    martial_arts_muay_thai: async () => (await loadShard("martial_arts")).subModules["martial_arts_muay_thai"],
    martial_arts_shaolin_kung_fu: async () => (await loadShard("martial_arts")).subModules["martial_arts_shaolin_kung_fu"],
    martial_arts_silat: async () => (await loadShard("martial_arts")).subModules["martial_arts_silat"],
    martial_arts_taekwondo: async () => (await loadShard("martial_arts")).subModules["martial_arts_taekwondo"],
    martial_arts_tai_chi: async () => (await loadShard("martial_arts")).subModules["martial_arts_tai_chi"],
    martial_arts_wing_chun: async () => (await loadShard("martial_arts")).subModules["martial_arts_wing_chun"],
    martial_arts_wushu: async () => (await loadShard("martial_arts")).subModules["martial_arts_wushu"],
    martial_arts_xing_yi_quan: async () => (await loadShard("martial_arts")).subModules["martial_arts_xing_yi_quan"],
    psiops_clairvoyance_and_telepathy: async () => (await loadShard("psiops")).subModules["psiops_clairvoyance_and_telepathy"],
    psiops_energy_manipulation: async () => (await loadShard("psiops")).subModules["psiops_energy_manipulation"],
    psiops_psi_fields: async () => (await loadShard("psiops")).subModules["psiops_psi_fields"],
    psiops_psionic_training: async () => (await loadShard("psiops")).subModules["psiops_psionic_training"],
    psiops_psionic_weaponry: async () => (await loadShard("psiops")).subModules["psiops_psionic_weaponry"],
    psiops_psychic_shielding: async () => (await loadShard("psiops")).subModules["psiops_psychic_shielding"],
    psiops_remote_viewing: async () => (await loadShard("psiops")).subModules["psiops_remote_viewing"],
    war_strategy_asymmetric_warfare: async () => (await loadShard("war_strategy")).subModules["war_strategy_asymmetric_warfare"],
    war_strategy_cyber_warfare_strategy: async () => (await loadShard("war_strategy")).subModules["war_strategy_cyber_warfare_strategy"],
    war_strategy_geopolitical_analysis: async () => (await loadShard("war_strategy")).subModules["war_strategy_geopolitical_analysis"],
    war_strategy_military_strategy: async () => (await loadShard("war_strategy")).subModules["war_strategy_military_strategy"],
    war_strategy_psychological_operations_tactics: async () => (await loadShard("war_strategy")).subModules["war_strategy_psychological_operations_tactics"],
    war_strategy_special_operations_planning: async () => (await loadShard("war_strategy")).subModules["war_strategy_special_operations_planning"],
    web_three_blockchain_fundamentals: async () => (await loadShard("web_three")).subModules["web_three_blockchain_fundamentals"],
    web_three_decentralized_applications: async () => (await loadShard("web_three")).subModules["web_three_decentralized_applications"],
    web_three_decentralized_identity_and_privacy: async () => (await loadShard("web_three")).subModules["web_three_decentralized_identity_and_privacy"],
    web_three_smart_contract_development: async () => (await loadShard("web_three")).subModules["web_three_smart_contract_development"],
    web_three_tokenomics_and_defi: async () => (await loadShard("web_three")).subModules["web_three_tokenomics_and_defi"],
    web_three_web_three_security_and_auditing: async () => (await loadShard("web_three")).subModules["web_three_web_three_security_and_auditing"],
    self_sovereignty_breaking_narcissistic_bonds: async () => (await loadShard("self_sovereignty")).subModules["self_sovereignty_breaking_narcissistic_bonds"],
    self_sovereignty_emotional_flashback_control: async () => (await loadShard("self_sovereignty")).subModules["self_sovereignty_emotional_flashback_control"],
    self_sovereignty_gaslighting_defense: async () => (await loadShard("self_sovereignty")).subModules["self_sovereignty_gaslighting_defense"],
    self_sovereignty_generational_curse_breaking: async () => (await loadShard("self_sovereignty")).subModules["self_sovereignty_generational_curse_breaking"],
    self_sovereignty_high_stakes_psychological_warfare: async () => (await loadShard("self_sovereignty")).subModules["self_sovereignty_high_stakes_psychological_warfare"],
    self_sovereignty_identity_reconstruction: async () => (await loadShard("self_sovereignty")).subModules["self_sovereignty_identity_reconstruction"],
    self_sovereignty_intuition_strengthening: async () => (await loadShard("self_sovereignty")).subModules["self_sovereignty_intuition_strengthening"],
    self_sovereignty_mental_fortress_tactics: async () => (await loadShard("self_sovereignty")).subModules["self_sovereignty_mental_fortress_tactics"],
    self_sovereignty_narcissist_proofing_your_life: async () => (await loadShard("self_sovereignty")).subModules["self_sovereignty_narcissist_proofing_your_life"],
    self_sovereignty_power_posture_and_speech: async () => (await loadShard("self_sovereignty")).subModules["self_sovereignty_power_posture_and_speech"],
    self_sovereignty_psychic_energy_shielding: async () => (await loadShard("self_sovereignty")).subModules["self_sovereignty_psychic_energy_shielding"],
    self_sovereignty_ritual_detachment_exercises: async () => (await loadShard("self_sovereignty")).subModules["self_sovereignty_ritual_detachment_exercises"],
    self_sovereignty_sovereign_mindset_programming: async () => (await loadShard("self_sovereignty")).subModules["self_sovereignty_sovereign_mindset_programming"],
    self_sovereignty_strategic_social_disengagement: async () => (await loadShard("self_sovereignty")).subModules["self_sovereignty_strategic_social_disengagement"],
    self_sovereignty_trauma_alchemy: async () => (await loadShard("self_sovereignty")).subModules["self_sovereignty_trauma_alchemy"],
    anti_psn_behavioral_and_microexpression_analysis: async () => (await loadShard("anti_psn")).subModules["anti_psn_behavioral_and_microexpression_analysis"],
    anti_psn_covert_psn_destruction_strategies: async () => (await loadShard("anti_psn")).subModules["anti_psn_covert_psn_destruction_strategies"],
    anti_psn_covert_psychological_self_defense: async () => (await loadShard("anti_psn")).subModules["anti_psn_covert_psychological_self_defense"],
    anti_psn_covertly_overthrowing_psn_controlled_systems: async () => (await loadShard("anti_psn")).subModules["anti_psn_covertly_overthrowing_psn_controlled_systems"],
    anti_psn_creating_a_narcissist_free_life_structure: async () => (await loadShard("anti_psn")).subModules["anti_psn_creating_a_narcissist_free_life_structure"],
    anti_psn_destabilizing_psn_narrative_control: async () => (await loadShard("anti_psn")).subModules["anti_psn_destabilizing_psn_narrative_control"],
    anti_psn_disrupting_psn_communication_networks: async () => (await loadShard("anti_psn")).subModules["anti_psn_disrupting_psn_communication_networks"],
    anti_psn_disrupting_psn_information_networks: async () => (await loadShard("anti_psn")).subModules["anti_psn_disrupting_psn_information_networks"],
    anti_psn_economic_and_legal_sabotage_of_psn_power: async () => (await loadShard("anti_psn")).subModules["anti_psn_economic_and_legal_sabotage_of_psn_power"],
    anti_psn_eliminating_vulnerability_to_psn_tactics: async () => (await loadShard("anti_psn")).subModules["anti_psn_eliminating_vulnerability_to_psn_tactics"],
    anti_psn_emotional_detachment_and_resistance: async () => (await loadShard("anti_psn")).subModules["anti_psn_emotional_detachment_and_resistance"],
    anti_psn_eradicating_psn_command_and_control_positions: async () => (await loadShard("anti_psn")).subModules["anti_psn_eradicating_psn_command_and_control_positions"],
    anti_psn_escaping_psychopathic_relationships: async () => (await loadShard("anti_psn")).subModules["anti_psn_escaping_psychopathic_relationships"],
    anti_psn_gaslighting_countermeasures: async () => (await loadShard("anti_psn")).subModules["anti_psn_gaslighting_countermeasures"],
    anti_psn_high_stakes_psn_encounter_tactics: async () => (await loadShard("anti_psn")).subModules["anti_psn_high_stakes_psn_encounter_tactics"],
    anti_psn_leveraging_social_resistance_movements: async () => (await loadShard("anti_psn")).subModules["anti_psn_leveraging_social_resistance_movements"],
    anti_psn_mental_warfare_and_cognitive_shielding: async () => (await loadShard("anti_psn")).subModules["anti_psn_mental_warfare_and_cognitive_shielding"],
    anti_psn_narcissist_red_flag_detection: async () => (await loadShard("anti_psn")).subModules["anti_psn_narcissist_red_flag_detection"],
    anti_psn_power_hierarchy_analysis_and_psn_mapping: async () => (await loadShard("anti_psn")).subModules["anti_psn_power_hierarchy_analysis_and_psn_mapping"],
    anti_psn_psn_infiltration_detection_and_exposure: async () => (await loadShard("anti_psn")).subModules["anti_psn_psn_infiltration_detection_and_exposure"],
    anti_psn_psychological_self_fortification: async () => (await loadShard("anti_psn")).subModules["anti_psn_psychological_self_fortification"],
    anti_psn_psychological_warfare_and_psn_social_exile: async () => (await loadShard("anti_psn")).subModules["anti_psn_psychological_warfare_and_psn_social_exile"],
    anti_psn_psychopath_vs_sociopath_vs_narcissist: async () => (await loadShard("anti_psn")).subModules["anti_psn_psychopath_vs_sociopath_vs_narcissist"],
    anti_psn_recruiting_psn_defectors: async () => (await loadShard("anti_psn")).subModules["anti_psn_recruiting_psn_defectors"],
    anti_psn_reverse_psychological_warfare_against_psns: async () => (await loadShard("anti_psn")).subModules["anti_psn_reverse_psychological_warfare_against_psns"],
    anti_psn_social_contagion_disruption: async () => (await loadShard("anti_psn")).subModules["anti_psn_social_contagion_disruption"],
    anti_psn_strategic_social_disengagement: async () => (await loadShard("anti_psn")).subModules["anti_psn_strategic_social_disengagement"],
    anti_psn_turning_psn_tactics_against_them: async () => (await loadShard("anti_psn")).subModules["anti_psn_turning_psn_tactics_against_them"],
    anti_psn_undoing_psn_trauma_bonding: async () => (await loadShard("anti_psn")).subModules["anti_psn_undoing_psn_trauma_bonding"],
    anti_psn_verbal_self_defense_against_manipulation: async () => (await loadShard("anti_psn")).subModules["anti_psn_verbal_self_defense_against_manipulation"],
    anti_psn_weaponizing_truth_against_psn_control: async () => (await loadShard("anti_psn")).subModules["anti_psn_weaponizing_truth_against_psn_control"],
    anti_tcs_idc_cbc_artificial_scarcity_as_a_control_method: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_artificial_scarcity_as_a_control_method"],
    anti_tcs_idc_cbc_black_ops_and_covert_agenda_awareness: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_black_ops_and_covert_agenda_awareness"],
    anti_tcs_idc_cbc_blackmail_based_control_structures: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_blackmail_based_control_structures"],
    anti_tcs_idc_cbc_bloodlines_and_elite_occult_pacts: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_bloodlines_and_elite_occult_pacts"],
    anti_tcs_idc_cbc_breaking_the_cycle_of_idc_control: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_breaking_the_cycle_of_idc_control"],
    anti_tcs_idc_cbc_countering_occult_and_psionic_warfare: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_countering_occult_and_psionic_warfare"],
    anti_tcs_idc_cbc_covert_operations_for_dismantling_idc: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_covert_operations_for_dismantling_idc"],
    anti_tcs_idc_cbc_creating_parallel_societies: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_creating_parallel_societies"],
    anti_tcs_idc_cbc_cult_network_analysis: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_cult_network_analysis"],
    anti_tcs_idc_cbc_dark_economics: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_dark_economics"],
    anti_tcs_idc_cbc_death_cult_symbolism_and_language_decoding: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_death_cult_symbolism_and_language_decoding"],
    anti_tcs_idc_cbc_dismantling_idc_power_centers: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_dismantling_idc_power_centers"],
    anti_tcs_idc_cbc_economic_warfare_resistance: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_economic_warfare_resistance"],
    anti_tcs_idc_cbc_energy_harvesting_exposure: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_energy_harvesting_exposure"],
    anti_tcs_idc_cbc_false_messianic_movements: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_false_messianic_movements"],
    anti_tcs_idc_cbc_financial_sovereignty: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_financial_sovereignty"],
    anti_tcs_idc_cbc_global_crime_network_exposure: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_global_crime_network_exposure"],
    anti_tcs_idc_cbc_human_trafficking_disruption_tactics: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_human_trafficking_disruption_tactics"],
    anti_tcs_idc_cbc_hypernormalization_and_mass_hypnosis_breaking: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_hypernormalization_and_mass_hypnosis_breaking"],
    anti_tcs_idc_cbc_idc_control_in_cultural_narratives: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_idc_control_in_cultural_narratives"],
    anti_tcs_idc_cbc_idc_hierarchical_mapping: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_idc_hierarchical_mapping"],
    anti_tcs_idc_cbc_infiltration_of_governments_and_institutions: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_infiltration_of_governments_and_institutions"],
    anti_tcs_idc_cbc_information_warfare_and_counterintelligence: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_information_warfare_and_counterintelligence"],
    anti_tcs_idc_cbc_legal_and_extralegal_self_protection: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_legal_and_extralegal_self_protection"],
    anti_tcs_idc_cbc_occult_psychological_warfare_and_mind_control: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_occult_psychological_warfare_and_mind_control"],
    anti_tcs_idc_cbc_political_cults: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_political_cults"],
    anti_tcs_idc_cbc_propaganda_and_psyops_defense: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_propaganda_and_psyops_defense"],
    anti_tcs_idc_cbc_ritual_abuse_survivor_deprogramming: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_ritual_abuse_survivor_deprogramming"],
    anti_tcs_idc_cbc_ritual_sacrifice_exposure: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_ritual_sacrifice_exposure"],
    anti_tcs_idc_cbc_social_engineering_and_cyber_security: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_social_engineering_and_cyber_security"],
    anti_tcs_idc_cbc_spiritual_fortification_against_cult_control: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_spiritual_fortification_against_cult_control"],
    anti_tcs_idc_cbc_strategic_disengagement_and_escape_tactics: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_strategic_disengagement_and_escape_tactics"],
    anti_tcs_idc_cbc_suffering_as_a_control_method: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_suffering_as_a_control_method"],
    anti_tcs_idc_cbc_tactical_survival_and_self_defense: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_tactical_survival_and_self_defense"],
    anti_tcs_idc_cbc_weaponization_of_new_age_spirituality: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_weaponization_of_new_age_spirituality"],
    anti_tcs_idc_cbc_weaponization_of_religion: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_weaponization_of_religion"],
    anti_tcs_idc_cbc_weaponized_ai_and_surveillance_resistance: async () => (await loadShard("anti_tcs_idc_cbc")).subModules["anti_tcs_idc_cbc_weaponized_ai_and_surveillance_resistance"],
    space_force_cyber_defense: async () => (await loadShard("space_force")).subModules["space_force_cyber_defense"],
    space_force_fleet_coordination_protocols: async () => (await loadShard("space_force")).subModules["space_force_fleet_coordination_protocols"],
    space_force_intelligence_and_analysis: async () => (await loadShard("space_force")).subModules["space_force_intelligence_and_analysis"],
    space_force_joint_space_operations: async () => (await loadShard("space_force")).subModules["space_force_joint_space_operations"],
    space_force_leadership_and_professionalism: async () => (await loadShard("space_force")).subModules["space_force_leadership_and_professionalism"],
    space_force_microgravity_readiness: async () => (await loadShard("space_force")).subModules["space_force_microgravity_readiness"],
    space_force_nebula_siege_resilience: async () => (await loadShard("space_force")).subModules["space_force_nebula_siege_resilience"],
    space_force_orbital_operations_planning: async () => (await loadShard("space_force")).subModules["space_force_orbital_operations_planning"],
    space_force_orbital_tactics_command: async () => (await loadShard("space_force")).subModules["space_force_orbital_tactics_command"],
    space_force_physical_and_resilience: async () => (await loadShard("space_force")).subModules["space_force_physical_and_resilience"],
    space_force_space_contingency_resilience: async () => (await loadShard("space_force")).subModules["space_force_space_contingency_resilience"],
    space_force_space_operations: async () => (await loadShard("space_force")).subModules["space_force_space_operations"],
    space_force_zero_gravity_conditioning: async () => (await loadShard("space_force")).subModules["space_force_zero_gravity_conditioning"]
} satisfies Record<string, () => Promise<TrainingSubModuleFile>>;
